baseURL = "https://ilai.academy/"
languageCode = "en-us"
title = "ILAI Academy"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true

  [params.author]
    name = "Dr. MTD Lakshan"
    email = "hello@ilai.academy"
